name: task_manager
description: A simple local task manager app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0 # <-- ПРОМЕНЕНА ВЕРСИЯ ТУК (от 0.19.0 на ^0.20.2)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  table_calendar: ^3.1.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.3
  android_alarm_manager_plus: ^4.0.4
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  speech_to_text: ^6.6.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  fl_chart: 0.68.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true